### ISSUE TITLE
install instructions off

### ISSUE THREAD

**Issue by Vkodthiv** [brandondocusen/CntxtJV#1]
The instuctions call for " Navigate to the directory , cd CntxtJV-main". There is no such folder. In any case i went ahead with the subsequent steps. Hitting this error . Can someone help?

`(cntxt) ➜  CntxtJV git:(main) python CntxtJV.py
Error importing regex components: failed to find libmagic.  Check your installation
Make sure all component files are in the 'regex_components' directory`

`(cntxt) ➜  CntxtJV git:(main) ✗ pip show python-magic
Name: python-magic
Version: 0.4.27`

**Comment by Vkodthiv** [comment]
I had to install libmagic on MacOs and the issue is resolved

**Comment by brandondocusen** [comment]
I see, will update install directions. Nice job working it out!
